manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.3.0-rc1
      import: true  # Import all modules to ensure all dependencies are available

  self:
    path: iot-venture-f25-the-circuiteers
